// Initial products data with the provided images
export const initialProducts = [
  {
    name: "Cross-Back Dining Chair",
    description: "Elegant cross-back dining chair with natural wooden seat and black metal frame. Perfect for modern and traditional interiors. Handcrafted with premium materials for lasting durability.",
    category: "Dining Room",
    price: 4999,
    originalPrice: 7999,
    rating: 4.7,
    reviews: 156,
    image: "/images/products/exclusiveproduct1.png",
    badge: "Best Seller",
    inStock: true,
    featured: true,
    isExclusive: false,  // Regular product with Buy Now
  },
  {
    name: "Industrial Bar Stool",
    description: "Adjustable height industrial bar stool with wooden seat and backrest. Features sturdy metal frame with footrest ring. Perfect for kitchen islands and bar counters.",
    category: "Seating",
    price: 8999,
    originalPrice: 12999,
    rating: 4.8,
    reviews: 203,
    image: "/images/products/exclusiveproduct2.png",
    badge: "Exclusive",
    inStock: true,
    featured: true,
    isExclusive: true,  // Exclusive product - WhatsApp only
    exclusivePrice: "Contact for Custom Price",
  },
  {
    name: "Geometric Side Table Set",
    description: "Set of 2 modern geometric side tables with metal cage design. Available in gold and black finish. Features wooden top and bottom shelf for extra storage.",
    category: "Living Room",
    price: 12999,
    originalPrice: 18999,
    rating: 4.6,
    reviews: 89,
    image: "/images/products/exclusiveproduct3.png",
    badge: "New Arrival",
    inStock: true,
    featured: true,
    isExclusive: false,  // Regular product with Buy Now
  },
  {
    name: "C-Shape Accent Table",
    description: "Contemporary C-shaped accent table with curved metal legs and wooden top. Perfect as a laptop table, side table, or plant stand. Space-saving design for modern homes.",
    category: "Living Room",
    price: 3999,
    originalPrice: 5999,
    rating: 4.5,
    reviews: 124,
    image: "/images/products/exclusiveproduct4.png",
    badge: "Best Value",
    inStock: true,
    featured: true,
    isExclusive: true,  // Exclusive product - WhatsApp only
    exclusivePrice: "Starting from ₹3,999",
  },
  {
    name: "Industrial Metal Chair",
    description: "Classic industrial metal dining chair with vintage finish. Stackable design perfect for cafes, restaurants, or modern homes. Durable powder-coated steel construction.",
    category: "Dining Room",
    price: 3499,
    originalPrice: 4999,
    rating: 4.6,
    reviews: 142,
    image: "/images/products/exclusiveproduct5.png",
    badge: "Popular",
    inStock: true,
    featured: true,
    isExclusive: true,  // Exclusive product - WhatsApp only
    exclusivePrice: "Contact for Bulk Pricing",
  },
];
